### ISSUE TITLE
换一个 TypeScript 的 Loader

### ISSUE THREAD

**Issue by squarepants** [ysmood/febone#2]
awesome-typescript-loader 会一直报 Can't find module xxx 的问题，这个找了作者解决也不是特别积极，而且不止是这个问题，还存在其他问题。

我们改成用 https://github.com/TypeStrong/ts-loader   这个是微软官方推荐的，之前遇到的报的所有的错其实都是各种变量的重复定义。

原因就是 http://stackoverflow.com/questions/31322525/typescript-confusing-duplicate-identifier-error-message

其实是我们的用法有问题，需要在 tsconfig.json 里加上 exclude: [ "node_modules" ]

这样就没问题了

```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by ysmood** [comment]
了解
